### PR TITLE
Feature/hamburger menu

### PR DESCRIPTION
**Pull request by torrober**
Hamburger menu proposal, 0% JS.

Built using `<details>` and checkbox responsible for menu toggle. 

image

### CODE REVIEW

**Review by rafamagers — APPROVED** [review]
Goos standarization

**Comment by torrober** [comment]
Thanks, implementin this in all pages and i will shortly merge

**Review by SantiagoR0214 — APPROVED** [review]
nice job

**Comment by torrober** [comment]
3/5, merging

**Pull request merged**
