### PR TITLE
Feature/uh2004 create shopping cart page

### PR DESCRIPTION
**Pull request by rafamagers**
**Shopping cart page implemented**
Please review it

image

### CODE REVIEW

**Comment by torrober** [comment]
please, remove any styles from the button, these will be standardized.

**Comment by rafamagers** [comment]
Let me fix it

**Comment by rafamagers** [comment]
Fixed it!

**Comment by rafamagers** [comment]
image

**Review by torrober — APPROVED** [review]
Okay, looks good.

**Pull request merged**
